# Generated by Django 5.0.3 on 2024-03-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("author", models.TextField()),
                ("genre", models.TextField()),
                ("status", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("image_url", models.URLField()),
            ],
        ),
    ]
